"""Add auth and owner_id

Revision ID: 3de0ad5c526c
Revises: 
Create Date: 2026-06-28 18:08:23.208094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de0ad5c526c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('config', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'config', 'users', ['owner_id'], ['id'])
    op.add_column('custom_agents', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_custom_agents_name'), table_name='custom_agents')
    op.create_index(op.f('ix_custom_agents_name'), 'custom_agents', ['name'], unique=False)
    op.create_foreign_key(None, 'custom_agents', 'users', ['owner_id'], ['id'])
    op.add_column('prospects', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'prospects', 'users', ['owner_id'], ['id'])
    op.add_column('trigger_sources', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'trigger_sources', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trigger_sources', type_='foreignkey')
    op.drop_column('trigger_sources', 'owner_id')
    op.drop_constraint(None, 'prospects', type_='foreignkey')
    op.drop_column('prospects', 'owner_id')
    op.drop_constraint(None, 'custom_agents', type_='foreignkey')
    op.drop_index(op.f('ix_custom_agents_name'), table_name='custom_agents')
    op.create_index(op.f('ix_custom_agents_name'), 'custom_agents', ['name'], unique=True)
    op.drop_column('custom_agents', 'owner_id')
    op.drop_constraint(None, 'config', type_='foreignkey')
    op.drop_column('config', 'owner_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
