"""remove_auth

Revision ID: 6dfd1add4387
Revises: 3de0ad5c526c
Create Date: 2026-06-28 18:33:36.119054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dfd1add4387'
down_revision: Union[str, None] = '3de0ad5c526c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('config_owner_id_fkey'), 'config', type_='foreignkey')
    op.drop_column('config', 'owner_id')
    op.drop_constraint(op.f('custom_agents_owner_id_fkey'), 'custom_agents', type_='foreignkey')
    op.drop_column('custom_agents', 'owner_id')
    op.drop_constraint(op.f('prospects_owner_id_fkey'), 'prospects', type_='foreignkey')
    op.drop_column('prospects', 'owner_id')
    op.drop_constraint(op.f('trigger_sources_owner_id_fkey'), 'trigger_sources', type_='foreignkey')
    op.drop_column('trigger_sources', 'owner_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('trigger_sources', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('trigger_sources_owner_id_fkey'), 'trigger_sources', 'users', ['owner_id'], ['id'])
    op.add_column('prospects', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('prospects_owner_id_fkey'), 'prospects', 'users', ['owner_id'], ['id'])
    op.add_column('custom_agents', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('custom_agents_owner_id_fkey'), 'custom_agents', 'users', ['owner_id'], ['id'])
    op.add_column('config', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('config_owner_id_fkey'), 'config', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
