"""hitl cascade ondelete

Revision ID: c4fe5ddfcc1b
Revises: a1b2c3d4e5f6
Create Date: 2026-06-28 23:30:16.878371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4fe5ddfcc1b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('hitl_requests_prospect_id_fkey'), 'hitl_requests', type_='foreignkey')
    op.create_foreign_key(None, 'hitl_requests', 'prospects', ['prospect_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_constraint(None, 'hitl_requests', type_='foreignkey')
    op.create_foreign_key(op.f('hitl_requests_prospect_id_fkey'), 'hitl_requests', 'prospects', ['prospect_id'], ['id'])
    # ### end Alembic commands ###
